she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('<int:pk>/update', views.UpdateStoryView.as_view(), name='updateStory'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/delete/', views.DeleteStory.as_view(), name='deleteStory'),
    path('author/<str:slug>/', views.ViewUsersStories.as_view(), name='usersStories')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name='createAccount'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='userProfile'),
    path('profile/<str:slug>/', views.UserProfileView.as_view(), name='userProfile'),
    # path('profile/update-account/', views.UpdateAccountView.as_view(), name='updateAccount')
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField(max_length=200, blank=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="stories"
    )

    def __str__(self):
        return self.title

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    #this is where I'd add other fields, e.g profile pic, bio
    bio = models.TextField(blank=True)
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm, SplitDateTimeField, SplitDateTimeWidget
from django.utils.translation import ugettext_lazy as _

from .models import NewsStory


class StoryForm(ModelForm):
    pub_date = SplitDateTimeField(
        widget = SplitDateTimeWidget(
            date_attrs={'type': 'date'},
            time_attrs={'type': 'time'},
        )   
    )
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image']
        labels = {
            'image' : _('Image (URL)'),
        }
        widgets = {
            'title' : forms.TextInput(attrs={'placeholder': 'Title'}),
            'content' : forms.Textarea(attrs={'placeholder': 'Story Content'}),
            'image' : forms.URLInput(attrs={'placeholder': 'Image URL'})
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from users.models import CustomUser
from .forms import StoryForm


class AddStoryView(LoginRequiredMixin, generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy("news:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdateStoryView(UserPassesTestMixin, generic.UpdateView):
    model = NewsStory
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy("news:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        """Return the keyword arguments for instantiating the form."""
        kwargs = super().get_form_kwargs()
        kwargs.update({'instance': self.get_object()})
        return kwargs

    def test_func(self):
        story = self.get_object()
        if self.request.user == story.author:
            return True
        return False
    


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class DeleteStory(UserPassesTestMixin, generic.DeleteView):
    model = NewsStory
    success_message = "Story: %(title)s has been deleted"

    def test_func(self):
        story = self.get_object()
        if self.request.user == story.author:
            return True
        return False

    def get_success_url(self):   
        storyId =self.kwargs['pk']
        story = self.get_object()
        print(story)
        author = story.author.username
        success_message = self.success_message % {'title': story.title}
        messages.success(self.request, success_message)
        print(success_message)
        return reverse_lazy("users:userProfile", kwargs = {'slug': author})

class ViewUsersStories(generic.DetailView):
    model = CustomUser
    template_name = 'news/usersStories.html'
    context_object_name = 'user'
    slug_field = 'username'
    

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'
   
    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        messages.success(self.request, f"Account created for {username}!")
        return super().form_valid(form)


class UserProfileView(LoginRequiredMixin, generic.DetailView):
    model = CustomUser
    template_name = 'users/userProfile.html'
    context_object_name = 'user'
    slug_field = 'username'



    
    

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div class="content-section">
    <form action="" id="story-form" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" id="story-btn" class="btn btn-outline-info">Submit</button>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% else %}
        <a href="{% url 'users:createAccount' %}">Become A Contributor</a>
    {% endif %}
    
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% else %}
        <a href="{% url 'users:createAccount' %}">Become A Contributor</a>
    {% endif %}
    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <a href="{% url 'news:usersStories' story.author.username %}"><h4>{{ story.author }}</h4></a>
        <h4>{{ story.pub_date }}</h4>
        <div id="story-content">
            <img src="{{ story.image }}">
            {{ story.content|linebreaks }}
            {% if user.is_authenticated and request.user == story.author %}
                <div id=story-btns class="form-group">
                    <form action="{% url 'news:updateStory' story.pk %}"  method="GET">
                        {% csrf_token %}
                        <button id="edit-btn" class="btn btn-outline-info" type="submit">Edit</button>
                    </form>
                    <form action="{% url 'news:deleteStory' story.pk %}"  method="POST">
                        {% csrf_token %}
                        <button id="delete-btn" class="btn btn-outline-info" type="submit">Delete</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
        {% if not story.image %}
            <a href="{% url 'news:story' story.id %}"><img class="story-img" src="https://picsum.photos/600"></a>
        {% else %}
            <a href="{% url 'news:story' story.id %}"><img class="story-img" src="{{ story.image }}"></a>
        {% endif %}
        <div class="story-card-text">
            <h3>
                <a href="{% url 'news:story' story.id %}">{{ story.title }}</a>
            </h3>
            <h4>
                <a href="{% url 'news:usersStories' story.author.username %}">{{ story.author }}</a>
            </h4>
            <h4>
                {{ story.pub_date }}
            </h4>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/usersStories.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% else %}
        <a href="{% url 'users:createAccount' %}">Become A Contributor</a>
    {% endif %}
    <div>
        <h3>Stories by author: {{ user.username }}</h3>
        <h4> Author Bio: {{ user.bio }} </h4>
    </div>
    <div id="all-stories">
        {% for story in object.stories.all %}
            {% include "news/storyCard.html" with story=story  %}
        {% endfor %}
    </div>
{% endblock %}

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Bronwyn Achemedei">
        <link href="https://fonts.googleapis.com/css2?family=News+Cycle:wght@400;700&display=swap" rel="stylesheet">
         <!-- bootstrap -->
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
         <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
         <link rel="stylesheet" href="{% static 'js/app.js' %}">
        {% block stylesheets %}
        {% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <p class="alert alert-{{ message.tags }}">
                {% if message.tags %} {% endif %}{{ message }}
            </p>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}
      <a href="{% url 'users:userProfile' request.user.username %}">{{ request.user }}</a>
      <a href="{% url 'logout'%}">Logout</a>
    {% else %}
      <a href="{% url 'login'%}">Login</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post'>
        {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Account</legend>
                {{ form|crispy }}
                <div class="form-group">
                    <button type='submit' class="btn btn-outline-info">Create Account</button>
                </div>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Already got an account? <a class="ml-2" href="{% url 'login'%}">Login here</a>
                    </small>
                </div>
            </fieldset>
    </form>
</div>

{% endblock %}

she_codes_news/users/templates/users/updateAccount.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post'>
        {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Account</legend>
                {{ form|crispy }}
                <div class="form-group">
                    <button type='submit' class="btn btn-outline-info">Update Account</button>
                </div>
                <div class="border-top pt-3">
                </div>
            </fieldset>
    </form>
</div>

{% endblock %}

she_codes_news/users/templates/users/userProfile.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}


{% block content %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% else %}
        <a href="{% url 'users:createAccount' %}">Become A Contributor</a>
    {% endif %}
    {{ request.GET.Delete }}
    <div id="profile-wrapper">
        <p>
            <h2>Your Details:</h2>
            <h4>Username: {{ user.username }}</h4>
            <h4>Email: {{ user.email }}</h4>
            <h5>Bio: {{user.bio }}</h4>
        </p>
    </div>
    <div id="all-stories">
        {% for story in object.stories.all %}
            {% include "news/storyCard.html" with story=story  %}
        {% endfor %}
    </div>
{% endblock %}